# Hyprpaper — wallpaper daemon
# To change wallpaper dynamically: hyprctl hyprpaper wallpaper "DP-1,~/Pictures/Wallpapers/some.jpg"

preload = $HOME/Pictures/Wallpapers/GABRIEL-5890.jpg.jpeg
wallpaper = ,$HOME/Pictures/Wallpapers/GABRIEL-5890.jpg.jpeg
splash = false
