[mgr]
sort_by      = "mtime"
sort_reverse = true
sort_dir_first = true

[opener]
play = [
    { run = 'mpv --hwdec=no --vo=gpu --gpu-context=wayland -- %s', orphan = true, for = "unix", desc = "mpv (GPU rendering)" },
]

[open]
prepend_rules = [
    { mime = "video/*", use = "play" },
]
